version: '3'
services:
  api:
    image: 'node:12.19.0'
    working_dir: /server
    ports:
      - 3000:3000
    environment: 
      - PORT=3000
      - PGUSER=chris
      - PGHOST=db
      - PGPASSWORD=greatpassok
      - PGDATABASE=login
      - PGPORT=5432
    depends_on: 
      - db
    volumes:
      - type: bind
        source: ./server/api
        target: /server
    command: bash -c "npm install && npm start"
  db:
    image: 'postgres:latest'
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./server/db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=login
      - POSTGRES_USER=chris
      - POSTGRES_PASSWORD=greatpassok
volumes:
  dbdata: